name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-tags:
          - ''
          - 'noquotas'
          - 'nocontpool noregpool'
          - 'noquotas nocontpool noregpool'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: All tests
      run: go test -tags '${{ build-tags }}' -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.txt
        name: codecov-all-tests
        verbose: true
    
    - name: Build CLI
      run: go build -tags '${{ build-tags }}'
